name: Create JI
author: harupy
description: Leaves a comment on an open PR matching a push event.
branding:
  icon: 'message-square'
  color: 'blue'
inputs:
  base_url:
    description: base_url
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
