name: Create JI
author: harupy
description: Leaves a comment on an open PR matching a push event.
inputs:
  base_url:
    description: base url
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
