name: comment-on-pr example
on: pull_request
jobs:
  example:
    name: sample comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: comment PR
        uses: ../github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
