name: comment-on-pr example
on: pull_request
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: comment PR
        uses: ./.github/actions/create-jira-link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base_url: https://www.google.com/
